services:
  mercado-livre-front:
    image: mercado-livre-front:0.1.0
    container_name: mercado-livre-front
    volumes:
      - ../front-end:/app
      - /app/node_modules
    ports:
      - "3040:3000"
    networks:
      - mercado-livre-network


  mercado-livre-back:
    image: mercado-livre-back:0.1.0
    container_name: mercado-livre-back
    volumes:
      - ../back-end:/app
      - /app/node_modules
    ports:
      - "3050:3001"
    command: sh -c "npm i && npx prisma generate && npm run start:dev"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mercado-livre-db:5432/mercado_livre?schema=public
    networks:
      - mercado-livre-network

  mercado-livre-db:
    image: postgres:16-alpine
    container_name: mercado-livre-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercado_livre
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mercado-livre-network

volumes:
  postgres-data:

networks:
  mercado-livre-network:
    driver: bridge